PREFIX dblp: <https://dblp.org/rdf/schema#>
CONSTRUCT {
  ?sig ?p ?o .
}
WHERE {
  {
    SELECT DISTINCT ?sig WHERE {
      ?pub dblp:publishedInStream <__STREAM__> .
      ?pub dblp:hasSignature ?sig .
    }
  }
  ?sig ?p ?o .
}
ORDER BY ?sig ?p ?o
LIMIT __LIMIT__
OFFSET __OFFSET__