PREFIX dblp: <https://dblp.org/rdf/schema#>
CONSTRUCT {
  ?stream ?p ?o .
}
WHERE {
  {
    SELECT DISTINCT ?stream WHERE {
      { BIND(<__STREAM__> AS ?stream) }
      UNION
      { <__STREAM__> dblp:subStream ?stream . }
      UNION
      { ?stream dblp:superStream <__STREAM__> . }
    }
  }
  ?stream ?p ?o .
}
ORDER BY ?stream ?p ?o
LIMIT __LIMIT__
OFFSET __OFFSET__